[package]
name = "aurorium"
authors = ["Phill030"]
version = "1.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["headers"] }
bpaf = "0.9.6"
chrono = "0.4.31"
env_logger = "0.10.1"
log = "0.4.20"
quick-xml = { version = "0.31.0", features = ["serialize"] }
quickxml_to_serde = { version = "0.5", features = ["json_types"] }
reqwest = "0.11.22"
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio-util = { version = "0.7.10", features = ["io-util", "rt"] }
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
console = "0.15.7"
indicatif = "0.17.7"
lazy_static = "1.4.0"
tower = { version = "0.4.13", features = ["limit"] }
