[package]
name = "aurorium"
authors = ["Phill030"]
version = "1.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["headers"] }
bpaf = "0.9.4"
chrono = "0.4.26"
env_logger = "0.10.0"
log = "0.4.20"
quick-xml = { version = "0.30.0", features = ["serialize"] }
quickxml_to_serde = { version = "0.5", features = ["json_types"] }
reqwest = "0.11.18"
rayon = "1.7.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tokio-util = { version = "0.7.8", features = ["io-util", "rt"] }
tokio = { version = "1.31.0", features = ["full"] }
futures = "0.3.28"
console = "0.15.7"
indicatif = "0.17.6"
# thiserror = "1.0.44"
