[package]
authors = ["Phill030"]
license-file = "LICENSE.md"
repository = "https://github.com/Phill030/Aurorium"
name = "aurorium_rework"
version = "4.0.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
chrono = "0.4.45"
indicatif = "0.18.6"
miette = { version = "7.6.0", features = ["fancy"] }
quick-xml = "0.41.0"
regex = "1.13.1"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = [
    "chrono",
    "env-filter",
    "registry",
] }
futures-util = "0.3.33"
rusqlite = { version = "0.40.1", features = ["bundled"] }
rusqlite_migration = "2.6.0"
async-sqlite = "0.6.0" # TODO: Remove default-features
serde_json = "1.0.151"
tower-http = { version = "0.7.0", features = ["fs"] }
tower = "0.5.3"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
