[package]
name = "aurorium"
authors = ["Phill030"]
version = "2.1.1"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
bpaf = "0.9.11"
chrono = "0.4.35"
console = "0.15.8"
env_logger = "0.11.3"
futures = "0.3.30"
lazy_static = "1.4.0"
log = "0.4.21"
quick-xml = { version = "0.31.0", features = ["serialize"] }
quickxml_to_serde = { version = "0.6.0", features = ["json_types"] }
regex = "1.10.4"
reqwest = "0.12.2"
rayon = "1.10.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
thiserror = "1.0.52"
tokio-util = { version = "0.7.10", features = ["io-util", "rt"] }
tokio = { version = "1.36.0", features = ["full"] }
async-trait = "0.1.79"
anyhow = "1.0.81"
