[package]
name = "AuroriumRewrite"
version = "3.0.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.37", features = ["derive", "env"] }
futures-util = "0.3.31"
indicatif = "0.17.11"
regex = "1.11.1"
reqwest = "0.12.15"
roxmltree = "0.20.0"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
